from enum import Enum


class ErrorCode(str, Enum):
    # General
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    BAD_REQUEST = "BAD_REQUEST"

    # Authentication
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    INVALID_TOKEN = "INVALID_TOKEN"

    # Market Data
    MARKET_DATA_UNAVAILABLE = "MARKET_DATA_UNAVAILABLE"
    INVALID_SYMBOL = "INVALID_SYMBOL"
    MARKET_API_TIMEOUT = "MARKET_API_TIMEOUT"

    # Fireworks AI
    FIREWORKS_ERROR = "FIREWORKS_ERROR"
    LLM_TIMEOUT = "LLM_TIMEOUT"

    # Vision
    INVALID_IMAGE = "INVALID_IMAGE"
    PATTERN_NOT_FOUND = "PATTERN_NOT_FOUND"

    # Portfolio
    PORTFOLIO_NOT_FOUND = "PORTFOLIO_NOT_FOUND"

    # Journal
    JOURNAL_NOT_FOUND = "JOURNAL_NOT_FOUND"

    # Database
    DATABASE_ERROR = "DATABASE_ERROR"

    # Redis
    CACHE_ERROR = "CACHE_ERROR"

    # Simulation
    SIMULATION_ERROR = "SIMULATION_ERROR"